### ISSUE TITLE
compile for arm64 architecture

### ISSUE THREAD

**Issue by tnaroska** [jhunt/s3#10]
Hi, any chance you could add arm64 targets for the linux and darwin builds?

Seems like it would only require two more entries in the makefile
https://github.com/jhunt/s3/blob/master/Makefile#L10-L11

Thanks!

**Comment by jhunt** [comment]
That should be doable!

**Comment by jhunt** [comment]
Try v0.3.2 binaries: https://github.com/jhunt/s3/releases/tag/v0.3.2

**Comment by tnaroska** [comment]
LGTM thanks!
